name: RELEASE api

on:
  push:
    branches: [ "stage" ]
    tags:
      - 'v3*'

permissions:
  contents: read

jobs:

# ------- START API PROCCESS -------- #

  TestAPI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Create environment and install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt
          pip install -e .

      - name: Run Tests with pytest
        env:
          DATABASE_URL: "sqlite:///:memory:"
        run: |
          source env/bin/activate
          PYTHONPATH=$PYTHONPATH:./src pytest src/tests/

# ------- END API PROCCESS -------- #

# ------- START MERGE PROCCESS -------- #

  MergeMainAPI:
    needs: [TestAPI]
    name: Merge Stage with Main
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Merge stage -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          head_to_merge: ${{ github.ref }}
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}

# ------- END MERGE PROCCESS -------- #

# ------- START RELEASE PROCCESS -------- #

  PostRelease:
    needs: MergeMainAPI
    name: Create Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Zip artifact for deployment
        run: zip releaseAPI.zip ./src/* -r

      - name: Upload API artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: API
          path: releaseAPI.zip

      - name: Generate Tagname for release
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: stage,main
          BRANCH_HISTORY: last
          CUSTOM_TAG_PREFIX: v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.taggerDryRun.outputs.new_tag }}
          release_name: Release ${{ steps.taggerDryRun.outputs.new_tag }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

      - name: Upload Release Asset API
        id: upload-api-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./releaseAPI.zip
          asset_name: releaseAPI.zip
          asset_content_type: application/zip

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Update version in setup.py
        run: |
          sed -i "s/version='.*'/version='${{ steps.taggerDryRun.outputs.new_tag }}'/" setup.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit version change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update version to ${{ steps.taggerDryRun.outputs.new_tag }}"

# ------- END RELEASE PROCCESS -------- #
